/*
 *
 * LoginScreen constants
 *
 */

export const DEFAULT_ACTION = 'app/LoginScreen/DEFAULT_ACTION';
export const REQUEST_AUTHENTICATION = 'app/LoginScreen/REQUEST_AUTHENTICATION';
export const UPDATE_AUTHENTICATION_ERROR = 'app/LoginScreen/UPDATE_AUTHENTICATION_ERROR';
export const REQUEST_AUTHENTICATION_SUCCESS = 'app/LoginScreen/REQUEST_AUTHENTICATION_SUCCESS';
export const REQUEST_AUTHENTICATION_FAILURE = 'app/LoginScreen/REQUEST_AUTHENTICATION_FAILURE';
